apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.cloudinary }}
  labels: {{- include "chat-backend.labels" . | nindent 4 }}
type: Opaque
data:
  cloudinary-name: 
  cloudinary-api-key: 
  cloudinary-api-secret: 
